apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysql-wordpress
spec:
  members: 1
  rootPasswordSecret:
    name: db-password
  volumeClaimTemplate:
    metadata:
      name: data
    spec:
      storageClassName: manual
      accessModes:
        - ReadWriteMany
      resources:
        requests:
          storage: 100Mi
