apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-wordpress
spec:
  selector:
    matchLabels:
      app: mysql-wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-wordpress
    spec:
      containers:
      - image: mariadb:10.4.12-bionic
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-password
              key: password
        ports:
          - containerPort: 3306
            name: mariadb
        volumeMounts:
          - name: mysql-local-volume
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-local-volume
        persistentVolumeClaim:
          claimName: mysql-claim