namespace: mysql-cluster
resources:
  - namespace.yaml
  - persistent-volume.yaml
  - persistent-volume-claim.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: db-password
    literals:
      - password=some_password
