apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-router
spec:
  selector:
    matchLabels:
      app: mysql-router
  template:
    metadata:
      labels:
        app: mysql-router
    spec:
      containers:
        - name: mysqlrouter
          image: mysql/mysql-router:8.0.19-0.9-router
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: mysql-wordpress.mysql-cluster.svc.cluster.local
            - name: MYSQL_INNODB_NUM_MEMBERS
              value: "1"
          ports:
            - containerPort: 6446
