apiVersion: rbac.authorization.k8s.io/v1beta1
kind:  ClusterRoleBinding
metadata:
  name: wordpress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind:  ClusterRole
  name: mysql-agent
subjects:
  - kind: ServiceAccount
    name: wordpress
    namespace: wordpress
