apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-volume
          persistentVolumeClaim:
            claimName: wordpress-claim
      containers:
        - name: wordpress
          image: wordpress:php7.4-fpm
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-wordpress.mysql-cluster.svc.cluster.local:3306
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/var/www/html"
              name: wordpress-volume
