namespace: wordpress
resources:
  - namespace.yaml
  - persistant-volume.yaml
  - persistant-volume-claim.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - deployment.yaml
  - service.yaml
  - ingress-configmap.yaml
  - ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: db-password
    literals:
      - password=some_password
