apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: wordpress
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 500Mi
  hostPath:
    path: /tmp
  persistentVolumeReclaimPolicy: Delete
  storageClassName: manual
